
server:
  port: 8222
spring:
  application:
    name: Department-Service
  zipkin:
    base-url: http://127.0.0.1:9411/
  h2:
    console:
      enabled: true
      path: /h3
  datasource:
    driver-class-name: org.h2.Driver
    username: pa
    password: pa
    url: jdbc:h2:mem:testdb
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect